### ISSUE TITLE
how to download mjai format paipu

### ISSUE THREAD

**Issue by hejinnoz** [Jim137/Tenhou-Paifu-Logger#29]
hi,thanks for your efforts ,do u know how to download mjai format paipu

**Comment by Jim137** [comment]
Thank you for your message! I'm glad to assist you. To convert a paipu XML file into the mjai format, you can utilize the [fstqwq/mjlog2mjai](https://github.com/fstqwq/mjlog2mjai) repository.

Here's an example of how to use it:

```
from parse import load_mjlog, parse_mjlog_to_mjai

mjlog_data = load_mjlog('<paipu_name>.xml')
mjai_data = parse_mjlog_to_mjai(mjlog_data)

with open('<paipu_name>.mjson', 'w', encoding='UTF-8') as f:
    f.write(mjai_data)
```

I'm currently working on adding this feature, and you can expect it in the upcoming release. If you have any more questions or need further assistance, feel free to ask!

**Comment by Jim137** [comment]
The latest release is now supporting the function of downloading mjai format paipu. Please check it out!🎉
